### ISSUE TITLE
Shitty code

### ISSUE THREAD

**Issue by TobleMiner** [TobleMiner/fahrschulcard#1]
Needs to be rewritten while NOT drunk:
- Much more universal DOM based HTML parsing
- More statistics

**Comment by TobleMiner** [comment]
Now 20% less shitty!  ![20% Rainbow Dash](http://2.bp.blogspot.com/-yo75VXeNuQE/VIJA5b_4GGI/AAAAAAACFbE/Fzr16Q8AoK0/s1600/rainbow_dash___dash_with_it_by_mysteriouskaos-d5cu0zq.png)

**Comment by TobleMiner** [comment]
I do no longer have access to the fahrschulcard website.

**Comment by AlphaKoreaner** [comment]
how can i get it ??
